version: '3'
services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: actionIsComing!
      ACCEPT_EULA: Y

  lti-provider:
    container_name: lti-provider
    build: .
    environment:
      LTI_DATABASE_URL: sqlserver://db:1433;user=sa;password=actionIsComing!;encrypt=true;trustServerCertificate=true;connectionTimeout=300;
      LTI_SECRET: secret
      JWT_SECRET: jwt_secret
    ports:
      - 7071:7071
    depends_on:
      - db
