name: deploy-server

on:
  push:
    branches:
      - demo
    paths-ignore:
      - README.md
      - e2e/**
      - solver/**
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://lti-linux.azurewebsites.net
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Setup Node 18.x Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        shell: bash
        run: |
          npm ci --install-strategy=nested
          npm run build -w server
          npm run build -w client
          mv client/dist server/static
          npm prune --production

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: "lti-linux"
          slot-name: "Production"
          package: ./server
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FDEE999359AE401ABA85F6752550B7A5 }}
