name: Run tests

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node 18.x Environment
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies
        shell: bash
        run: |
          npm install

      - name: Lint and format
        shell: bash
        run: |
          npm run lint -w server
          npm run lint -w client
          npm run format -w server
          npm run format -w client

      - name: Run tests
        shell: bash
        run: |
          npm run test -w server -- --watch false
